### ISSUE TITLE
Standardize TAP file name

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#236]
Currently, TKG creates TAP file called `TestTargetResult.tap`. Since we are going to collect the TAP files for AQAvit certification, we will collect TAP files for all test builds. It means we can get lots of these TAP files (the more parallel runs that we have, the more files we will have). We need to standardize the TAP file name. This will help us to easily identify the level and group of the tap file and display the results in the Grid view in TRSS. Also, putting this at the TKG level will benefit automated and local runs.

I would suggest creating a TAP file name based on JDK_VERSION, IMPL, TARGET, and PLATFORM info (similar to Jenkins test job name)- Test_openjdk<JDK_VERSION>_<JDK_IMPL>_<TARGET>_<PLATFORM>.tap
i.e., Test_openjdk8_j9_sanity.openjdk_ppc64_aix.tap. 
Also, the user can set this filename. If the value is not provided by the user, TKG should generate the tap file name as above.

**Comment by amandanguyeen** [comment]
Forgot to comment, but I can take this on!
