### ISSUE TITLE
Add spec sunos_x86-64 and osx_aarch64 to ottawa.csv

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/TKG#245]
Add spec sunos_x86-64 and osx_aarch64 to ottawa.csv to make sure correct mode running on those spec.

**Comment by JeromeJu** [comment]
Working on #245

**Comment by JeromeJu** [comment]
Closing as Mode1000 shall only be run on 32-bit platforms, so no necessary work to be carried out for SunOS.
https://github.com/adoptium/TKG/pull/261

**Comment by JeromeJu** [comment]
**For the osx support:**
Thanks to knn_k, the osx_aarch64 support shall be updated in the following PR [link](https://github.com/adoptium/TKG/pull/258)

**Comment by smlambert** [comment]
re: https://github.com/adoptium/TKG/issues/245#issuecomment-1019360976 - it was noticed that the VENDOR_TEST_DIRS were not getting set to /test/functional so the SmokeTests were failing to load and not being compiled which ultimately resulted in them not being run.  The entry for sunos_x86-64 is correct in ottawa.csv.
