### ISSUE TITLE
Create a metadata file for AQAvit certification use case

### ISSUE THREAD

**Issue by smlambert** [adoptium/TKG#260]
As part of the AQAvit certification use case, vendors wishing to certify need to provide both the test results in the form of TAP files (which are already produced by TKG), and metadata that contains information about the "object under test" (the JDK binary).

We already print some of this information to console, but do not capture it into a file for easy archiving.

This issue is to both discuss and determine the initial required set of information to capture, but also to then enhance TKG to produce the metadata file during a test run.

Information that should be included are:
- java -version output
- information regarding the tags/SHAs of the 'object under test' - for OpenJ9 this information is in the java -version output, for hotspot, we have to extract it by other means

**Comment by llxia** [comment]
The issue for Archive the metadata file is created at aqa-tests repo: https://github.com/adoptium/aqa-tests/issues/3264

**Comment by JeromeJu** [comment]
Would like to start on this :)

**Comment by llxia** [comment]
Release info: https://github.com/adoptium/aqa-tests/blob/master/get.sh#L596-L601
