### ISSUE TITLE
Create a feature tag for test

### ISSUE THREAD

**Issue by renfeiw** [adoptium/TKG#268]
We need a mechanism to control a test against a JDK feature, for example AOT, CRIU, etc. We already had some tags such as `<aot>` to control tests, but it only works for aot. We need a generalized way to handle any upcoming feature. This will replace the `<aot>` tag.

Here is the result of the work explained with AOT as an example, we can define one of the following options for a test. For other features, just replace AOT with the feature name that's defined in TEST_FLAG. Multiple `<feature>` can be enclosed in one `<features>`.
```
<features>
           <feature>AOT:applicable</feature> ------ This is the default option. The test will run whether or not TEST_FLAG contains 
AOT (Special treatment will be applied when TEST_FLAG contains AOT, it will be run multiple times and special JVM option will be 
applied)
           <feature>AOT:nonapplicable</feature> ------ The test will NOT run when TEST_FLAG contains AOT
           <feature>AOT:explicit</feature> ------ The test will run whether or not TEST_FLAG contains AOT (No special treatment will 
be applied when TEST_FLAG contains AOT, the test will run as-is) Currently, this option is only meaningful for AOT.
           <feature>AOT:required</feature> ------ the test will run ONLY when TEST_FLAG contains AOT (Special treatment will be 
applied)
</features>
```

**Comment by llxia** [comment]
related https://github.com/eclipse-openj9/openj9/issues/14016
