### ISSUE TITLE
Add documentation to liveMonitor and count tests feature

### ISSUE THREAD

**Issue by smlambert** [adoptium/TKG#280]
There is no documentation for the features available in https://github.com/adoptium/TKG/tree/master/scripts/liveMonitor_countTests and we should capture the basic description of these scripts, expected use case and how to use them in a simple README.md file in the scripts/liveMonitor_countTests folder. 

For whoever takes on this issue, the expectation is to try using both scripts, reading through the issue under which they were added, and then create basic documentation for others to use.

**Comment by JeromeJu** [comment]
I would like to work on this @smlambert :)

I've noticed that there are some notes in the [aqa-test docs](https://github.com/adoptium/aqa-tests/blob/master/doc/userGuide.md#use-live_monitor-feature) may I ask if that's the place I should add the use cases/ documentations to?

Thank you!

**Comment by smlambert** [comment]
Thanks @JeromeJu!  To answer your question, for now, we can put the documentation into a new https://github.com/adoptium/TKG/tree/master/scripts/liveMonitor_countTests/README.md file.  As we build out all of the AQAvit documentation, we can reference the various pieces from a central file in the aqa-tests repo.

**Comment by JeromeJu** [comment]
While the count-java-test script is fairly simple, with the following output:

```jeromeju@Jeromes-MacBook-Pro TKG % python3 -u scripts/liveMonitor_countTests/count-java-tests.py ../openjdk/openjdk-jdk/test/langtools/tools/javac/warnings

Counting tests in '../openjdk/openjdk-jdk/test/langtools/tools/javac/warnings' ...

Found 47 java files

. ................ 14 
6594914 ........... 2 
6747671 ........... 1 
6885255 ........... 1 
7090499 ........... 1 
AuxiliaryClass .... 3 
DefaultCtor ....... 3 
NestedDeprecation . 1 

suppress ......... 10 


Found 36 java files containing @test```
