### ISSUE TITLE
Display rebuild link in local case only

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#286]
In Jenkins, users can use `Rerun in Grinder` link or `Rerun failed tests in Grinder` link once https://github.com/adoptium/aqa-tests/issues/3219 is completed. To avoid confusion, we should only display rebuild in the local case. Code that needs to be updated: 
https://github.com/adoptium/TKG/blob/eb1a3a0c34c5f809c6aefe714b15a83f44b19f39/scripts/resultsSum.pl#L258-L301

**Details**:
- if $ENV{'HUDSON_URL'} is defined, do nothing
- if $ENV{'HUDSON_URL'} is not defined, create rebuild link. Move the existing logic under if block
```
if ((!defined $hudsonUrl) || ($hudsonUrl eq '')) {
...
}
```

- remove all Jenkins specific parameters - jenkinsParam

**Comment by YeeSkywalker** [comment]
Hi @llxia, it would be greatly appreciated if you could assign this issue to me!

**Comment by YeeSkywalker** [comment]
For anyone needs to install Apache Ant on Mac OS, it could be a more intuitive way:

1. Download binary file ends with `.zip` from [Apache Ant Binary Distributions](https://ant.apache.org/bindownload.cgi).
2. Unzip the file and rename the folder as 'ant'.
3. Open the Home finder window and drag the ant folder into the Home directory.
4. In the terminal, run the command `cd ant/bin; pwd`, you will get something like /User/(your username)/ant/bin, copy it for later usage.
5. Run the command `cd  ~` which will bring you back to the Home directory.
6. Run the command `open -e .bash_profile`, a bash window will pop up.
7. Insert`export PATH=${PATH}:` followed by the link you just copy
8. In the terminal, type `. ~/.bash_profile`
9. You are good to go! ☺️

**Comment by llxia** [comment]
I believe this issue is resolved.
