### ISSUE TITLE
TKG exits with non-zero value if there is any test failure

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#301]
This is related to https://github.com/eclipse-openj9/openj9/issues/14322. TAP plugin may fail with special characters in the test output. When this happens, we may only see the previously processed tests. In some cases (only passed tests are processed), the test builds that reply on TAP result may have a false-positive status. To avoid this problem, I would suggest TKG exits with non-zero if there is any test failure. The test pipeline should check both TAP file and TKG returns.

**Comment by sophia-guo** [comment]
This might be related with  the Jenkins agent encoding. Could someone try setting the agent JVM with  -Dfile.encoding=UTF-8? If it doesn't work may also need to check Locale of the system by looking at the environment variables if LANG=en_US.UTF-8?
