### ISSUE TITLE
Support machine info detection in TKG

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#336]
Some tests may only run on certain micro-architecture. TKG should check micro-architecture on the machine and execute/skip tests accordingly. Frome example, some VectorAPI tests only run on Z13/Z14 or newer, CRIU portability tests run on skylake, etc. This feature may further extend to check other machine info (i.e., RAM, CPU, application installed, etc) as needed.

TKG runs cmd to detect the machine info:

- cmd for detecting skylake
```
cat /proc/cpuinfo | grep 'model name' | uniq
```
- cmd for detecting z version with newer openj9 JDK:
```
$ ./semaru/bin/java -Xshareclasses:none -Xjit:verbose -version 2>&1 | grep Name:
#INFO:          Name: z15
```

`platformRequirements ` in playlist.xml should be enhanced for setting specific hardware or software requirements.

Related issue:
runtimes/openj9-jit-z/issues/711
runtimes/infrastructure/issues/7037
https://github.com/adoptium/TKG/issues/45#issuecomment-1167750455

**Comment by smlambert** [comment]
Would also like a check for whether we are in a containerized environment or not, something like this:
`if grep -sq 'docker\|lxc' /proc/1/cgroup; then    echo "I am running on Docker."; else echo "not docker "; fi`

**Comment by smlambert** [comment]
It seems like both the support for microArch and a PR for docker info was merged.  Can this issue be closed?  

Noting a separate issue was raised to detect Podman versus Docker https://github.com/adoptium/TKG/issues/503, so I would not hold this issue open for that.

**Comment by llxia** [comment]
Issue https://github.com/adoptium/TKG/issues/471 is for z versions.
