### ISSUE TITLE
No AQACert.log and SHA.txt content on windows

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#363]
There is no AQACert.log and SHA.txt content in TAP file on windows:
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.functional_x86-64_windows/
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.functional_x86-64_windows/lastSuccessfulBuild/artifact/aqa-tests/TKG/output_16658700363494/Test_openjdk11_j9_sanity.functional_x86-64_windows.tap/*view*/
```
# AQACert.log content: 
# 
#SHA.txt content: 
# 
# Timestamp: Sun Oct 16 00:32:19 2022 UTC 
1..358
ok 1 - cmdLineTester_bootstrapMethodArgumentTest_0 
  ---
    duration_ms: 4553
  ...
ok 2 - cmdLineTester_callsitedbgddrext_openj9_0 
  ---
    duration_ms: 87664
...
```

The expected behaviour would be that we would see the same type of information as retrieved during a run on a Linux or Mac platform (see TAP file from [recent run](https://ci.adoptium.net/view/Test_grinder/job/Grinder/11897/) on Linux)
```
#SHA.txt content: 
# ================================================
# timestamp: 20241129-143946
# repo dir: /home/jenkins/workspace/Grinder/aqa-tests
# git repo: 
#   Fetch URL: https://github.com/adoptium/aqa-tests.git
# sha:
# a7f0676ca19bf949745b8dc2964c52dcef4df9a2
# ================================================
# timestamp: 20241129-143946
# repo dir: /home/jenkins/workspace/Grinder/aqa-tests/TKG
# git repo: 
#   Fetch URL: https://github.com/AdoptOpenJDK/TKG.git
# sha:
# 4ab5104cbc97d54ce0deb26c9d69e4380a796922
# ================================================
# timestamp: 20241129-143952
# repo dir: /home/jenkins/workspace/Grinder/aqa-tests/openj9
# git repo: 
#   Fetch URL: https://github.com/eclipse/openj9.git
# sha:
# 9049e87fa8ee536e41916450e43760bcb4420ffe
# 
# Timestamp: Fri Nov 29 20:40:55 2024 UTC 
# TEST TARGETS RESULTS SUMMARY: TOTAL: 6   EXECUTED: 5   PASSED: 5   FAILED: 0   DISABLED: 1   SKIPPED: 0
```

Rerunning that [same test on Windows](https://ci.adoptium.net/view/Test_grinder/job/Grinder/11898/) produces this TAP output
```
# AQACert.log content: 
# 
# Hostname: test-azure-win-2

#SHA.txt content: 
# 
# Timestamp: Fri Nov 29 20:42:25 2024 UTC 
# TEST TARGETS RESULTS SUMMARY: TOTAL: 6   EXECUTED: 4   PASSED: 4   FAILED: 0   DISABLED: 2   SKIPPED: 0
```

**Comment by chandrashritii** [comment]
Hey @smlambert @llxia I'd like to take this up. Can you please assign this issue to me?

**Comment by smlambert** [comment]
Adding note from Slack [conversation](https://adoptium.slack.com/archives/C5219G28G/p1732188629039859) with Toshitaka Ogata:


> This information is obtained via cat command in resultsSum.pl. (https://github.com/adoptium/TKG/blob/1cd98d0ef8004e1300cf104785acc51a2e7205cb/scripts/resultsSum.pl#L355)
On Windows, the operand of the cat command contains unescaped backslashes, such as /path_to_aqatests/TKG\output\../AQACert.log, which seems to cause this problem. I think, escaping backslashes or replacing them with slashes would solve this issue.

**Comment by smlambert** [comment]
Seems to be a missing `\` between TKG and output_xxxtimestampxxx folder
```
15:42:26  cat: 'C:/jenkins/workspace/Grinder/aqa-tests/TKGoutput_17329129243908../AQACert.log': No such file or directory
15:42:26  cat: 'C:/jenkins/workspace/Grinder/aqa-tests/TKGoutput_17329129243908../SHA.txt': No such file or directory
```
