### ISSUE TITLE
Support for spurrious failure in commandline tests

### ISSUE THREAD

**Issue by tajila** [adoptium/TKG#421]
Currently commandline tests have the following conditions: success, require and failure. There are cases were a test may fail due to some infra or OS issues completely unrelated to the test. In some of these cases these failures may be expected (and even tolerated). Currently there is no way to convey this info in cmdline test. 

This issue is especially relevant for CRIU. When doing an on-host checkpoint/restore, if the OS cannot acquire the same thread IDs for restore, then restore will fail, and this is expected. The workaround we have been using is that we have elimated the use of required conditions post checkpoint and we have made test success as well as OS failures a "success" condition. While this approach does work it does make deciphering the test conditions more complex.

I think what we need is a spurious failure condition (doesn't have to be called this). When this condition is met the test is marked as skipped regardless of what the other conditions are.

**Comment by tajila** [comment]
@llxia Please let me know if this is not the correct place to make this issue.

**Comment by llxia** [comment]
The condition (to skip or not) can only be determined at runtime? If so, we may need to get more details about the scenario.

Also, commandline tester code is in openj9 repo https://github.com/eclipse-openj9/openj9/tree/master/test/functional/cmdline_options_tester

If the feature is intended for commandline tester, then the issue should be in openj9 repo. We can talk more about this once we have a better understanding of the use case.

**Comment by tajila** [comment]
> The condition (to skip or not) can only be determined at runtime? If so, we may need to get more details about the scenario.

Okay, perhaps skip is not the best outcome, but the intention is that these spurious failures do not fail the test. Essentially, I'd like a way to handled known flakiness.

> If the feature is intended for commandline tester, then the issue should be in openj9 repo. We can talk more about this once we have a better understanding of the use case.

Okay, Ill re-open in the J9 repo
