### ISSUE TITLE
Standalone compilation is broken for JDK21 during autogen phase with DYNAMIC_COMPILE=true

### ISSUE THREAD

**Issue by smlambert** [adoptium/TKG#482]
Error summary: 
**cannot find the following tests: compile**

---

Failure when attempting to run local testing via command-line, fails to find the `compile` target:

```
make -f makeGen.mk AUTO_DETECT= MODE=buildList TESTTARGET=compile TESTLIST=
make[1]: Entering directory '/Users/shelley_lambert@ca.ibm.com/work2/aqa-tests/TKG'
perl scripts/configure.pl
/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home//bin/java -cp "./bin/TestKitGen.jar:/json-simple.jar" org.testKitGen.MainRunner --mode=buildList --spec=osx_x86-64 --microArch= --osLabel="" --jdkVersion=21 --impl=hotspot --vendor="eclipse" --buildList=openjdk --iterations=1 --aotIterations= --testFlag= --testTarget=compile --testList= --numOfMachines= --testTime= --TRSSURL= 
Modes data parsed from resources/modes.xml and resources/ottawa.csv.


Starting to generate build list.

Parsing /Users/shelley_lambert@ca.ibm.com/work2/aqa-tests/TKG/../openjdk/playlist.xml
Generated /Users/shelley_lambert@ca.ibm.com/work2/aqa-tests/TKG/../TKG/buildInfo.mk

Error: cannot find the following tests: compile (note: group target such as sanity is not accepted inside testList)

make[1]: *** [makeGen.mk:45: autogen] Error 1
make[1]: Leaving directory '/Users/shelley_lambert@ca.ibm.com/work2/aqa-tests/TKG'
make: *** [makefile:91: buildListGen] Error 2

```

This was reported against a case where BUILD_LIST=functional, but has been reproduced with BUILD_LIST=openjdk also.

USE_TESTENV_PROPERTIES=true
BUILD_LIST=functional
JDK_VERSION=21
DYNAMIC_COMPILE=true
TARGET=sanity.functional 
JDK_IMPL=hotspot

were the settings this was first reported on.

Appears related to DYNAMIC_COMPILE=true setting.

**Comment by smlambert** [comment]
When switching DYNAMIC_COMPILE=false and running from the v0.9.9-release branch to compile OPENJ9_BRANCH=v0.41.0-release functional test material, there is a separate compilation failure (issue raised here: 
https://github.com/eclipse-openj9/openj9/issues/18620).

**Comment by sophia-guo** [comment]
I've tried aqa-tests master with Microsoft jdk21 https://aka.ms/download-jdk/microsoft-jdk-21.0.1-macOS-aarch64.tar.gz locally. Can't reproduce it.

**Comment by smlambert** [comment]
Closing as will not address in the v0.9.9-release branch.
