### ISSUE TITLE
TKG checks Docker version, but not Podman

### ISSUE THREAD

**Issue by LongyuZhang** [adoptium/TKG#503]
Currently TKG has the function of checking Docker version, but for machines with Podman, it will show 
`docker : not on docker`
We can add a similar function to check Podman too.

**Comment by llxia** [comment]
https://github.com/adoptium/TKG/blob/6e73a9fa473738b6e92c7a65e59588b5b0f408a8/src/org/openj9/envInfo/MachineInfo.java#L232

**Comment by llxia** [comment]
We should check both `docker --version` and `podman --version`. Please update the current CHECK_DOCKER_CMD and add check for podman.

**Comment by llxia** [comment]
@sophiaxu0424 please take a look at this issue. Thanks

**Comment by llxia** [comment]
PR https://github.com/adoptium/TKG/pull/565
