### ISSUE TITLE
Enhance Test result summary with testcases results

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/TKG#510]
Currently test result summary is provided by Targets level, which doesn't provide an accurate test information per test cases. It might be helpful if test summary per test cases could be provided. 

Both of JCK and JDK tests provide test summary per testcase (`Test results: passed: 41; failed: 5; error:1; skipped: 1`), which means this can be done for JCK and JDK tests.

Console output for each run could be something like:

```
TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++:
DISABLED test targets:
	jdk_awt_1
        ...
	jdk_sound_0

PASSED test targets:
        jdk_beans_2  - Test results: passed: 41; skipped: 1
        ...
  	jdk_other_2 - Test results: passed: 21

FAILED test targets:
        jdk_tools_2 - Test results: passed: 41; failed: 5; error:1; skipped: 1
        ...
        jdk_lang_1 -  Test results: passed: 541; failed: 5
TOTAL: 40   EXECUTED: 7   PASSED: 6   FAILED: 1   DISABLED: 11   SKIPPED: 22
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++:
 
TESTCASES RESULTS SUMMARY: passed: 214; failed: 1; error: 0; skipped: 0  
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
Correspondingly tap file could also include those information for passed ones if needed ( failed one already include those information)

```
#SHA.txt content: 
...
# TEST TARGETS RESULTS SUMMARY: TOTAL: 2   EXECUTED: 2   PASSED: 1   FAILED: 1   DISABLED: 0   SKIPPED: 0
# TESTCASES RESULTS SUMMARY: passed: 214; failed: 1; error: 0; skipped: 0 
1..2
ok 1 - jdk_math_0
  ---
    output:
      |
        Test results: passed: 39
    duration_ms: 100014
  ...
not ok 2 - jdk_security1_0
  ---
    output:
      |
        Failed test cases: 
        TEST: java/security/cert/CertPathBuilder/akiExt/AKISerialNumber.java
        Test results: passed: 175; failed: 1
    duration_ms: 95974
  ...
```

Thoughts @smlambert @jiekang ?

**Comment by sophia-guo** [comment]
Related https://github.com/adoptium/aqa-tests/issues/5121

**Comment by smlambert** [comment]
Big +1 to this suggestion, since once this info is put to the console, we can also grab it for inclusion to TRSS DB and relates to https://github.com/adoptium/aqa-test-tools/issues/841

**Comment by jiekang** [comment]
The additional information sounds good to me!
