### ISSUE TITLE
Enhance Test cases results summary - iteration 2

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/TKG#522]
Enhance Test cases results summary - second iteration of #510 . Issues found or requests

- Test cases results like `Test results: passed: 1,010` is skipped by testcase result summary, https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.openjdk_x86-64_linux/34/consoleFull, Similar issues happens to jck tests results
 - extra blank lines https://github.com/adoptium/TKG/issues/522#issuecomment-2009633784
 - summary results number format https://github.com/adoptium/TKG/issues/522#issuecomment-2009654078

**Comment by smlambert** [comment]
In this phase of iterative improvement of this enhancement, it will also be good to remove extra blank lines if possible.

**Comment by sophia-guo** [comment]
Might also good to add ','  to final result summary with big numbers

TESTCASES RESULTS SUMMARY: **passed: 32019**; failed: 0; error: 0; skipped: 63 --> TESTCASES RESULTS SUMMARY: **passed: 32,019**; failed: 0; error: 0; skipped: 63
