### ISSUE TITLE
Mode questions

### ISSUE THREAD

**Issue by knn-k** [adoptium/TKG#529]
I have some questions on [ottawa.csv](https://github.com/adoptium/TKG/blob/master/resources/ottawa.csv).  What are these modes for?

**Mode155**:
It is enabled only on linux_390-64 and linux_aarch64 configurations.
https://github.com/adoptium/TKG/blob/232682673cdbd1a4b818b2b7e13bf4ea39f844c3/resources/modes.xml#L1076
https://github.com/adoptium/TKG/blob/232682673cdbd1a4b818b2b7e13bf4ea39f844c3/resources/ottawa.csv#L62

**Mode198 and Mode199**:
These modes use the `-Xaggressive` option, and are enabled only on win_x86-64 and linux_aarch64 configurations.
https://github.com/adoptium/TKG/blob/232682673cdbd1a4b818b2b7e13bf4ea39f844c3/resources/modes.xml#L1945
https://github.com/adoptium/TKG/blob/232682673cdbd1a4b818b2b7e13bf4ea39f844c3/resources/modes.xml#L1966
https://github.com/adoptium/TKG/blob/232682673cdbd1a4b818b2b7e13bf4ea39f844c3/resources/ottawa.csv#L91-L92

**Comment by knn-k** [comment]
It seems that I enabled these modes on linux_aarch64_cmprssptrs by mistake when I added the platform by https://github.com/adoptium/TKG/pull/40.
I opened PR #531 as a fix.

**Comment by knn-k** [comment]
PR #40 enabled Modes 158 and 159 by mistake.
PR #528 fixes Mode158, and #531 fixes Mode159.

**Comment by llxia** [comment]
> What are these modes for?

The mode is a short name for a list of jvm options. We inherited the old logic from vmfarm.
As you listed above,
- [TKG/resources/modes.xml](https://github.com/adoptium/TKG/blob/master/resources/modes.xml) - defines the list of jvm options for each mode
- [TKG/resources/ottawa.csv](https://github.com/adoptium/TKG/blob/master/resources/ottawa.csv) - defines what mode can or cannot run on which platforms. The complexity escalates when it needs to support non-cmprssptrs, cmprssptrs, and mixed JVM using one file.

**Comment by knn-k** [comment]
I think I should have been more clear.
I know what modes.xml and ottawa.csv are used for.  I wanted to know the purposes of Modes 155, 198, and 199 specifically.
I am disabling those modes on AArch64 Linux by #531 any way.
