### ISSUE TITLE
Remove view/Dependencies from asmtools URL

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#546]
We should use a direct 3rd party downloading URL, not a view. If the view changes, the URL will be invalid.

https://github.com/adoptium/TKG/blob/e9d595ec71f6e33dba769424a4435823a70276d5/scripts/getDependencies.pl#L128

Remove `view/Dependencies` from the URL:

https://ci.adoptium.net/job/dependency_pipeline/lastSuccessfulBuild/artifact/asmtools/asmtools-core-7.0.b10-ea.jar

**Comment by diyorbekibragimov** [comment]
i'll do it

**Comment by llxia** [comment]
@diyorbekibragimov are you still working on this? If not, that is ok. Just let us know. Thanks

**Comment by IamLRBA** [comment]
@smlambert this would be a good issue to start with and get acquainted with the project. I'd like to be assigned.
Thanks!
