### ISSUE TITLE
testDependency jars are improperly tagged when downloaded via curl

### ISSUE THREAD

**Issue by psoujany** [adoptium/TKG#600]
We see testDependency/llib/*.jars pre-exists and found jar files are tagged as `IBM-1047 T=on`. Due to this tagging ant compilation for Java21 fails. 

We would like to remove testDependency/lib on all z/OS machines and make BINARY tagging to jars. 

For more details refer : openj9-openjdk-jdk21-zos/issues/281

**Comment by psoujany** [comment]
Modified getDependencies.pl to tag jars as binary. Verifying the changes.

**Comment by psoujany** [comment]
@AdamBrousseau Could you please remove testDependency directory on all 2.5 and 3.1 z/OS machines. Thank you.

**Comment by AdamBrousseau** [comment]
>Could you please remove testDependency directory on all 2.5 and 3.1 z/OS machines.

Done on hyc jenkins
