### ISSUE TITLE
Request to retag TKG for Oct 2024 release

### ISSUE THREAD

**Issue by llxia** [adoptium/TKG#609]
https://github.com/adoptium/aqa-tests/pull/5524 is delivered into https://github.com/adoptium/aqa-tests/tree/v1.0.4-release. However, it has a dependent TKG change https://github.com/adoptium/TKG/pull/591. And this change is not in https://github.com/adoptium/TKG/releases/tag/v1.0.4.

For the Oct 2024 release, we request that TKG be tagged again. Assume it should be v1.0.4.1

@smlambert are you ok with it?

FYI @jasonkatonica @JasonFengJ9

**Comment by smlambert** [comment]
Yes, v1.0.4.1 is how this will need to be handled and then an update to the testenv.properties file in the v1.0.4-release branch of aqa-tests.  Will you take care of it @llxia ?

**Comment by llxia** [comment]
testenv.properties update: https://github.com/adoptium/aqa-tests/pull/5594

**Comment by llxia** [comment]
The change is delivered. This issue can be closed.
